services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_URL=db
      - DATABASE_PORT=5432
      - GROQ_API_KEY=${GROQ_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MCDA_URL=http://mcda:8081
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      mcda:
        condition: service_started
    volumes:
      - ./Backend:/app
    networks:
      - app-network
    command: >
      bash -c "
        python scripts/flush_redis.py &&
        python scripts/reset_db.py &&
        python scripts/load_data.py &&
        python scripts/deduplicate_companies.py &&
        uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      "

  frontend:
    build: 
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000  # Backend URL
      - CHOKIDAR_USEPOLLING=false  # Better for macOS performance
    stdin_open: true  # Enable interactive mode
    tty: true        # Enable terminal
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: ankane/pgvector:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    command: postgres -c 'listen_addresses=*'
    volumes:
      - ./Backend/docker/postgres/init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  mcda:
    build:
      context: ./HaskellMCDA
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge