kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
  - hostPath: /Users/macbook/Documents/All projects/Infineon Assignment/Investment-Search/Backend
    containerPath: /backend-source
